apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-service-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      type: backend
      app: posts-service
  template:
    metadata:
      labels:
        type: backend
        app: posts-service
    spec:
      containers:
        - name: posts-service-container
          image: listonfermi/wenet-posts-service
          envFrom:
            - configMapRef:
                name: posts-service-env
---
apiVersion: v1
kind: Service
metadata:
  name: posts-service-srv
spec:
  selector:
    type: backend
    app: posts-service
  ports:
    - name: posts-service-ports
      protocol: TCP
      port: 5001
      targetPort: 5001